version: '3.6'

services:
  rendertex:
    image: rendertex
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - redis
    env_file:
      - .env.local 
    environment:
      NODE_ENV: development 
    ports:
      - 8080:8080
  redis: 
    image: redis:alpine
    hostname: redis
    ports:
      - 6379:6379

