version: "3.6"

services:
  rendertex:
    image: rendertex
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      NODE_ENV: production
    ports:
      - 8090:8080
  redis: 
    image: redis:alpine
    hostname: redis
    ports:
      - 6379:6379